spring:
  application:
    name: notification-service

  datasource:
    url: jdbc:postgresql://localhost:5432/notification_db
    username: notification_user
    password: 12345
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 60000

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8080
