spring:
  application:
    name: notification-service

  datasource:
    url: jdbc:postgresql://localhost:5432/Template
    username: postgres
    password: postgresql2024
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8080
